"""Add namaad and OverallHistoryRecord

Revision ID: 09c8d9f3718a
Revises: 
Create Date: 2019-10-09 19:33:30.027243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c8d9f3718a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namaad',
    sa.Column('i', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('i')
    )
    op.create_table('overall_histrory_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namaad_id', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('closing_price', sa.Integer(), nullable=True),
    sa.Column('last_trade_price', sa.Integer(), nullable=True),
    sa.Column('first_price', sa.Integer(), nullable=True),
    sa.Column('yesterday_price', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['namaad_id'], ['namaad.i'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overall_histrory_record')
    op.drop_table('namaad')
    # ### end Alembic commands ###
